version: "3.8"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - looklook_net
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: kafka
      # KAFKA_ADVERTISED_PORT: 9092

      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # KAFKA_LISTENERS: PLAINTEXT://:9092

      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - looklook_net

  #  #搜集kafka业务日志、存储prometheus监控数据
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    user: root
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Shanghai
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - looklook_net
  #查看elasticsearch数据
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    container_name: kibana
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - looklook_net
  #消费kafka中filebeat收集的数据输出到es
  # go-stash:
  #   image: kevinwan/go-stash:1.0 # if you "macOs intel" or "linux amd"
  #   #    image: kevinwan/go-stash:1.0-arm64 #  if you "macOs m1" or "linux arm"
  #   container_name: go-stash
  #   user: root
  #   restart: always
  #   volumes:
  #     - ./deploy/go-stash/etc:/app/etc
  #   depends_on:
  #     - elasticsearch
  #     - kafka
  #   networks:
  #     - looklook_net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.0
    container_name: logstash
    restart: always
    volumes:
      - ./deploy/logstash/config.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - 5044:5044
    networks:
      - looklook_net
    depends_on:
      - elasticsearch
      - kafka

networks:
  looklook_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
